### ISSUE TITLE
feature request: could you document these url variables a little better?

### ISSUE THREAD

**Issue by karezza** [nemonik/taiga-helm#3]
The following need to be changed after setting up an ingress, but its not obvious how:
```
env: 
  taigaURL: "http://localhost:9000"
  taigaWebsocketsURL: "ws://localhost:9000"
  taigaSitesDomain: "localhost:9000"
  taigaSitesScheme: "http"
```
